/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

import baseDatos.AccionesJDBC;
import baseDatos.ActividadesJDBC;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keigo
 */
public class Agregar_Acciones extends javax.swing.JPanel {

    String nombre;
    String fechainicio;
    String fechalimite;
    String estado;
    String FI;
    String FL;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    AccionesJDBC accionesJDBC;

    /**
     * Creates new form Agregar_Acciones
     */
    public Agregar_Acciones() throws Exception {
        accionesJDBC = new AccionesJDBC();
        initComponents();
        
        Class.forName("org.postgresql.Driver");
        Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Euclick", "postgres", "Keigomitsui77");
        try {
            Statement st = con.createStatement();

            String sql = "select id_actividad, nombre_actividad from actividad";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                String id = String.valueOf(rs.getInt("id_actividad"));
                String Nombre = rs.getString("nombre_actividad");

                String tbData[] = {id, Nombre};
                DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();

                tblModel.addRow(tbData);
            }
            con.close();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancelarBtn = new javax.swing.JButton();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        fechaLim = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        fldAccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        guardarBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rdenproceso = new javax.swing.JRadioButton();
        rdpendientes = new javax.swing.JRadioButton();
        rdfinalizadas = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(544, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, -1, -1));
        jPanel1.add(fechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));
        jPanel1.add(fechaLim, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jButton2.setText("Agregar Tareas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        txtid.setToolTipText("");
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 88, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre Actividad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 282, 87));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Nombre de la accion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 32, -1, -1));

        fldAccion.setText("Nombre de la accion");
        fldAccion.setPreferredSize(null);
        jPanel1.add(fldAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 31, 210, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Fecha de Inicio");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Fecha limite");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(guardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Finalizadas");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, 20));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("Pendientes");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, 20));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("En proceso");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, 20));

        rdenproceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdenprocesoActionPerformed(evt);
            }
        });
        jPanel1.add(rdenproceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, 20));

        rdpendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdpendientesActionPerformed(evt);
            }
        });
        jPanel1.add(rdpendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, 20));

        rdfinalizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdfinalizadasActionPerformed(evt);
            }
        });
        jPanel1.add(rdfinalizadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, 20));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setText("Estado de la actividad");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jLabel4.setText("Ingrese el id de la actividad:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Agregar_Tarea newFrame = null;
        try {
            newFrame = new Agregar_Tarea();
        } catch (Exception ex) {
            Logger.getLogger(Agregar_Acciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        newFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    public boolean stringEstaVacio(String cadena) {
        if (cadena.isEmpty()) {
            return true;
        } else {
            return false;
        }
    }
    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        
        int diafi, mesfi, yearfi, diafl, mesfl, yearfl;
        if (!stringEstaVacio(txtid.getText()) && !stringEstaVacio(fldAccion.getText())) {
            nombre = fldAccion.getText();
            diafi = fechaInicio.getCalendar().get(Calendar.DAY_OF_MONTH);
            mesfi = fechaInicio.getCalendar().get(Calendar.MONTH);
            yearfi = fechaInicio.getCalendar().get(Calendar.YEAR);
            fechainicio = yearfi + "-" + mesfi + "-" + diafi;

            diafl = fechaLim.getCalendar().get(Calendar.DAY_OF_MONTH);
            mesfl = fechaLim.getCalendar().get(Calendar.MONTH);
            yearfl = fechaLim.getCalendar().get(Calendar.YEAR);
            fechalimite = yearfl + "-" + mesfl + "-" + diafl;
            int id_estado = accionesJDBC.Idestado(estado);
            FI = fechainicio;
            FL = fechalimite;
            int id = Integer.parseInt(txtid.getText());
            accionesJDBC.insertarAcc(nombre, FI, FL, id_estado, id);
        } else {
            JOptionPane.showMessageDialog(null,
                    "Ingrese el ID de la actividad para continuar por favor", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        this.setVisible(false);

    }//GEN-LAST:event_guardarBtnActionPerformed

    private void rdenprocesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdenprocesoActionPerformed
        estado = "en proceso";
    }//GEN-LAST:event_rdenprocesoActionPerformed

    private void rdpendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdpendientesActionPerformed
        estado = "pendiente";
    }//GEN-LAST:event_rdpendientesActionPerformed

    private void rdfinalizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdfinalizadasActionPerformed
        estado = "finalizada";
    }//GEN-LAST:event_rdfinalizadasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBtn;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private com.toedter.calendar.JDateChooser fechaLim;
    private javax.swing.JTextField fldAccion;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdenproceso;
    private javax.swing.JRadioButton rdfinalizadas;
    private javax.swing.JRadioButton rdpendientes;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
