/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Pantallas;

import java.awt.BorderLayout;
import pantallas.AgregarEspacioTrabajo;
import pantallas.espacio_de_trabajo;
import pantallas.estadopantallatablero;

/**
 *
 * @author user
 */
public class pantallaTablero extends javax.swing.JFrame {

    /** Creates new form pantallaEditarperfil */
    public pantallaTablero() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelusuario = new javax.swing.JLabel();
        lbltuerca = new javax.swing.JLabel();
        lblnombrefirma = new javax.swing.JLabel();
        btnmenu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblpartesup = new javax.swing.JLabel();
        lblpartelat = new javax.swing.JLabel();
        btnaggacti = new javax.swing.JButton();
        lblevaluaciones = new javax.swing.JLabel();
        lblacciones = new javax.swing.JLabel();
        panelpendientes = new javax.swing.JScrollPane();
        listpendientes = new javax.swing.JList<>();
        panelenproceso = new javax.swing.JScrollPane();
        listaenproceso = new javax.swing.JList<>();
        panelfinaladas = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(1760, 690));
        setResizable(false);
        getContentPane().setLayout(null);

        labelusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logousuario.png"))); // NOI18N
        getContentPane().add(labelusuario);
        labelusuario.setBounds(1260, 70, 55, 55);

        lbltuerca.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbltuerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logotuerca.png"))); // NOI18N
        lbltuerca.setText("jLabel1");
        lbltuerca.setMaximumSize(new java.awt.Dimension(50, 50));
        lbltuerca.setMinimumSize(new java.awt.Dimension(50, 50));
        getContentPane().add(lbltuerca);
        lbltuerca.setBounds(15, 47, 50, 50);

        lblnombrefirma.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblnombrefirma.setText("Euclick");
        getContentPane().add(lblnombrefirma);
        lblnombrefirma.setBounds(80, 50, 148, 45);

        btnmenu.setBackground(new java.awt.Color(255, 255, 204));
        btnmenu.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnmenu.setText("Menú");
        btnmenu.setAlignmentX(0.5F);
        btnmenu.setBorder(null);
        btnmenu.setBorderPainted(false);
        btnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnmenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnmenu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btnmenu);
        btnmenu.setBounds(10, 160, 310, 40);

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setText("Ejercicios de trabajo");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 205, 310, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton2.setText("Dashboard");
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 247, 310, 40);

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton3.setText("Configuración");
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 289, 310, 40);

        lblpartesup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/partesuperior2.png"))); // NOI18N
        getContentPane().add(lblpartesup);
        lblpartesup.setBounds(0, 0, 1760, 140);

        lblpartelat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/partelateral.png"))); // NOI18N
        getContentPane().add(lblpartelat);
        lblpartelat.setBounds(0, 140, 330, 560);

        btnaggacti.setBackground(new java.awt.Color(255, 255, 204));
        btnaggacti.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnaggacti.setText("+ Agregar Actividad");
        btnaggacti.setBorder(null);
        btnaggacti.setBorderPainted(false);
        btnaggacti.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
<<<<<<< HEAD
=======
        btnaggacti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaggactiMouseClicked(evt);
            }
        });
>>>>>>> 7b9cc65122100705edfbf767e0f390b58d949793
        getContentPane().add(btnaggacti);
        btnaggacti.setBounds(1160, 150, 250, 40);

        lblevaluaciones.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblevaluaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblevaluaciones.setText("Evaluaciones");
        lblevaluaciones.setToolTipText("");
        getContentPane().add(lblevaluaciones);
        lblevaluaciones.setBounds(350, 150, 250, 40);

        lblacciones.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblacciones.setText("Acciones");
        getContentPane().add(lblacciones);
        lblacciones.setBounds(370, 200, 250, 40);

        panelpendientes.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        listpendientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pendiente", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listpendientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listpendientes.setName(""); // NOI18N
        panelpendientes.setViewportView(listpendientes);
        listpendientes.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(panelpendientes);
        panelpendientes.setBounds(360, 500, 460, 120);

        panelenproceso.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        panelenproceso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        listaenproceso.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "En proceso", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        panelenproceso.setViewportView(listaenproceso);

        getContentPane().add(panelenproceso);
        panelenproceso.setBounds(360, 240, 460, 120);

        panelfinaladas.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Terminadas", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelfinaladas.setViewportView(jList1);

        getContentPane().add(panelfinaladas);
        panelfinaladas.setBounds(360, 370, 460, 120);
        getContentPane().add(content);
        content.setBounds(860, 190, 540, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnaggactiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaggactiMouseClicked
        estadopantallatablero pT = new estadopantallatablero();
        pT.setSize(540,470);
        pT.setLocation(0,0);
        
        content.removeAll();
        content.add(pT, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnaggactiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaTablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaggacti;
    private javax.swing.JButton btnmenu;
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JLabel labelusuario;
    private javax.swing.JLabel lblacciones;
    private javax.swing.JLabel lblevaluaciones;
    private javax.swing.JLabel lblnombrefirma;
    private javax.swing.JLabel lblpartelat;
    private javax.swing.JLabel lblpartesup;
    private javax.swing.JLabel lbltuerca;
    private javax.swing.JList<String> listaenproceso;
    private javax.swing.JList<String> listpendientes;
    private javax.swing.JScrollPane panelenproceso;
    private javax.swing.JScrollPane panelfinaladas;
    private javax.swing.JScrollPane panelpendientes;
    // End of variables declaration//GEN-END:variables

}
