/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class pantallaRegistro extends javax.swing.JFrame {
    /**
     * Creates new form pantallaRegistro
     */
    
    int xMouse,yMouse;
    public pantallaRegistro() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        btnconti = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        txtrepass = new javax.swing.JPasswordField();
        btnpassvis = new javax.swing.JToggleButton();
        btnrepassvis = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbltuerca = new javax.swing.JLabel();
        btnvolver = new javax.swing.JButton();
        lblnombrefirma = new javax.swing.JLabel();
        lblsesion = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.darkGray);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1050, 690));
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreKeyPressed(evt);
            }
        });
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 227, 24));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 131, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Apellido");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 131, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Correo");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 131, -1));

        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtapellidoKeyPressed(evt);
            }
        });
        jPanel2.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 227, 24));

        txtcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcorreoKeyPressed(evt);
            }
        });
        jPanel2.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 227, 24));

        btnconti.setText("Crear cuenta");
        btnconti.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnconti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontiActionPerformed(evt);
            }
        });
        jPanel2.add(btnconti, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 128, 40));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Contraseña");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 131, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("Reingresar contraseña");
        jLabel5.setToolTipText("");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, -1));

        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassKeyPressed(evt);
            }
        });
        jPanel2.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 227, 24));

        txtrepass.setMinimumSize(new java.awt.Dimension(14, 24));
        txtrepass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtrepassKeyPressed(evt);
            }
        });
        jPanel2.add(txtrepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 227, 24));

        btnpassvis.setText("ø");
        btnpassvis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnpassvis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpassvisMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnpassvisMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnpassvisMouseReleased(evt);
            }
        });
        btnpassvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpassvisActionPerformed(evt);
            }
        });
        jPanel2.add(btnpassvis, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 40, 30));

        btnrepassvis.setText("ø");
        btnrepassvis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnrepassvis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnrepassvisMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnrepassvisMouseReleased(evt);
            }
        });
        jPanel2.add(btnrepassvis, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 40, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Mínimo 5 caracteres");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Ingrese la contraseña nuevamente");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel8.setText("Registrarse");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 270, 60));

        lbltuerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logotuerca.png"))); // NOI18N
        jPanel2.add(lbltuerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 60));

        btnvolver.setBackground(java.awt.Color.black);
        btnvolver.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnvolver.setForeground(java.awt.Color.white);
        btnvolver.setText("Volver");
        btnvolver.setToolTipText("");
        btnvolver.setBorder(null);
        btnvolver.setBorderPainted(false);
        btnvolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnvolver.setFocusPainted(false);
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        jPanel2.add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 130, 40));

        lblnombrefirma.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblnombrefirma.setText("Euclick");
        jPanel2.add(lblnombrefirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 148, -1));

        lblsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logopersonasalir.png"))); // NOI18N
        lblsesion.setText("jLabel9");
        jPanel2.add(lblsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 70, -1));

        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 180, 600));

        jPanel1.setBackground(new java.awt.Color(88, 104, 117));
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1050, 60));

        exitBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        exitBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitBtn.setText("X");
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        jPanel2.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1007, 0, 40, 30));

        jPanel3.setBackground(new java.awt.Color(88, 104, 117));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    protected void iniciarBotones(){
        btnvolver.setForeground(Color.DARK_GRAY);
    }
    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btncontiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontiActionPerformed
        String nombre = txtnombre.getText();
        String apellido = txtapellido.getText();
        String correo = txtcorreo.getText();
        String pass = txtpass.getText();
        String repass = txtrepass.getText();
        if (nombre.equals("")){
             JOptionPane.showMessageDialog(this, "Ingrese su nombre para continuar"," Fallo de creacion de cuenta",JOptionPane.ERROR_MESSAGE);;
        }else{
            
        }
        
        JOptionPane.showMessageDialog(null, "Solicitud enviada correctamente, por favor verifíque su correo para confirmarlo");
    }//GEN-LAST:event_btncontiActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
       Login newframe =  new Login();
       newframe.setVisible(true);
       this.dispose();
       
       
    }//GEN-LAST:event_btnvolverActionPerformed

    private void txtnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String nombre = txtnombre.getText();
             txtapellido.requestFocus();
        }
    }//GEN-LAST:event_txtnombreKeyPressed

    private void btnpassvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpassvisActionPerformed
        
    }//GEN-LAST:event_btnpassvisActionPerformed

    private void btnpassvisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpassvisMouseClicked
        
    }//GEN-LAST:event_btnpassvisMouseClicked

    private void btnpassvisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpassvisMousePressed
        txtpass.setEchoChar((char)0);
    }//GEN-LAST:event_btnpassvisMousePressed

    private void btnpassvisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpassvisMouseReleased
        txtpass.setEchoChar('*');
    }//GEN-LAST:event_btnpassvisMouseReleased

    private void btnrepassvisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrepassvisMousePressed
        txtrepass.setEchoChar((char)0);
    }//GEN-LAST:event_btnrepassvisMousePressed

    private void btnrepassvisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrepassvisMouseReleased
        txtrepass.setEchoChar('*');
    }//GEN-LAST:event_btnrepassvisMouseReleased

    private void txtapellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String apellido = txtapellido.getText();
             txtcorreo.requestFocus();
        }
    }//GEN-LAST:event_txtapellidoKeyPressed

    private void txtcorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String correo = txtcorreo.getText();
             txtpass.requestFocus();
        }
    }//GEN-LAST:event_txtcorreoKeyPressed

    private void txtpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String pass = txtpass.getText();
             txtrepass.requestFocus();
        }
    }//GEN-LAST:event_txtpassKeyPressed

    private void txtrepassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrepassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String repass = txtrepass.getText();
            if (txtpass.getText().equals(repass)){
                JOptionPane.showMessageDialog(null, "Solicitud enviada correctamente, por favor verifíque su correo para confirmarlo");
                }else{
                JOptionPane.showMessageDialog(null, "Las contraseñas no son iguales, reintente por favor");
                txtpass.setText(null);
                txtrepass.setText(null);
                txtpass.requestFocus();
            }
        }
    }//GEN-LAST:event_txtrepassKeyPressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel3MouseReleased

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconti;
    private javax.swing.JToggleButton btnpassvis;
    private javax.swing.JToggleButton btnrepassvis;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblnombrefirma;
    private javax.swing.JLabel lblsesion;
    private javax.swing.JLabel lbltuerca;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JPasswordField txtrepass;
    // End of variables declaration//GEN-END:variables

}
